const reels = [
    {
    username: "john_doe",
    likeCount: 12450,
    isLiked: true,
    commentCount: 432,
    caption: "Sunsets hit different 🌅",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=1",
    shareCount: 187,
    isFollowed: false,
    },

    {
    username: "emma_writes",
    likeCount: 8950,
    isLiked: false,
    commentCount: 210,
    caption: "Coffee + Books = Perfect Morning ☕📚",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=5",
    shareCount: 95,
    isFollowed: true,
    },

    {
    username: "travelwithalex",
    likeCount: 28740,
    isLiked: true,
    commentCount: 921,
    caption: "Lost in the mountains 🏔️",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=12",
    shareCount: 563,
    isFollowed: true,
    },

    {
    username: "fitlife_sam",
    likeCount: 15430,
    isLiked: false,
    commentCount: 367,
    caption: "No excuses. Just results 💪",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=18",
    shareCount: 241,
    isFollowed: false,
    },

    {
    username: "foodie_riya",
    likeCount: 20390,
    isLiked: true,
    commentCount: 512,
    caption: "Homemade pasta tastes the best 🍝",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=25",
    shareCount: 324,
    isFollowed: true,
    },

    {
    username: "techwithmax",
    likeCount: 17800,
    isLiked: false,
    commentCount: 289,
    caption: "Coding late nights 💻✨",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=30",
    shareCount: 176,
    isFollowed: false,
    },

    {
    username: "nature_snap",
    likeCount: 32450,
    isLiked: true,
    commentCount: 1104,
    caption: "The beauty of waterfalls 🌊",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=36",
    shareCount: 740,
    isFollowed: true,
    },

    {
    username: "daily_vibes",
    likeCount: 11220,
    isLiked: false,
    commentCount: 198,
    caption: "Small moments, big memories ❤️",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=42",
    shareCount: 121,
    isFollowed: false,
    },

    {
    username: "musiclover",
    likeCount: 26780,
    isLiked: true,
    commentCount: 854,
    caption: "Music heals everything 🎵",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=48",
    shareCount: 458,
    isFollowed: true,
    },
    
    {
    username: "creative_anu",
    likeCount: 9480,
    isLiked: false,
    commentCount: 145,
    caption: "Sketching my imagination 🎨",
    video: "",
    userprofile: "https://i.pravatar.cc/150?img=52",
    shareCount: 82,
    isFollowed: false,
    },
];